// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_y_8pkMAuhpsL9hj-xBZwYc2z8F8vB6I',
    appId: '1:741827791438:web:58a65f8e06f9faa4f4911f',
    messagingSenderId: '741827791438',
    projectId: 'markov-sm4',
    authDomain: 'markov-sm4.firebaseapp.com',
    storageBucket: 'markov-sm4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBefmWbNpCbHrlVxSss_dvS5vtO7wJ7RrI',
    appId: '1:741827791438:android:40c0856c7ba2dfa2f4911f',
    messagingSenderId: '741827791438',
    projectId: 'markov-sm4',
    storageBucket: 'markov-sm4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDItXa4Jsx74A0g7u8Q2DRWZyNeVrYNhbs',
    appId: '1:741827791438:ios:f0ffa5cffbbadddaf4911f',
    messagingSenderId: '741827791438',
    projectId: 'markov-sm4',
    storageBucket: 'markov-sm4.appspot.com',
    iosBundleId: 'com.example.virtualBuddyAppDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDItXa4Jsx74A0g7u8Q2DRWZyNeVrYNhbs',
    appId: '1:741827791438:ios:f0ffa5cffbbadddaf4911f',
    messagingSenderId: '741827791438',
    projectId: 'markov-sm4',
    storageBucket: 'markov-sm4.appspot.com',
    iosBundleId: 'com.example.virtualBuddyAppDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_y_8pkMAuhpsL9hj-xBZwYc2z8F8vB6I',
    appId: '1:741827791438:web:f60ddb0ab7840803f4911f',
    messagingSenderId: '741827791438',
    projectId: 'markov-sm4',
    authDomain: 'markov-sm4.firebaseapp.com',
    storageBucket: 'markov-sm4.appspot.com',
  );
}
